controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_demand_index:
    path: /demand/
    controller: App\Controller\DemandController::index

app_demand_new:
    path: /demand/new/
    controller: App\Controller\DemandController::new

app_demand_show:
    path: /demand/{id}
    controller: App\Controller\DemandController::show

app_demand_edit:
    path: /demand/{id}/edit
    controller: App\Controller\DemandController::edit

app_demand_delete:
    path: /demand/{id}/delete
    controller: App\Controller\DemandController::delete

app_product_index:
    path: /product/
    controller: App\Controller\ProductController::index

app_product_new:
    path: /product/new/
    controller: App\Controller\ProductController::new

app_product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show

app_product_edit:
    path: /product/{id}/edit
    controller: App\Controller\ProductController::edit

app_product_delete:
    path: /product/{id}/delete
    controller: App\Controller\ProductController::delete
